apiVersion: v1
kind: Service
metadata:
  name: redis-headless-service
  namespace: redis-cluster
  labels:
    app: redis-cluster-app
spec:
  ports:
    - name: redis-port
      port: 6379
  clusterIP: None
  selector:
    app: redis-cluster-app
